// Redux also suggest defining constants for your action types.
export const setActionTypes = {
  USERS_LOADED: "USERS_LOADED",
  USERS_LOADING: "USERS_LOADING",
  USERS_LOADING_ERROR: "USERS_LOADING_ERROR",
  USER_LOADED: "USER_LOADED",
  USER_LOADING: "USER_LOADING",
  USER_LOADING_ERROR: "USER_LOADING_ERROR"
  // SELECT_USER: "SELECT_USER"
};
